runtime: python
env: flex
entrypoint: python application.py

runtime_config:
  python_version: 3

readiness_check:
  check_interval_sec: 300
  timeout_sec: 300

manual_scaling:
  instances: 2

resources: 
  disk_size_gb: 1000